name: Build the Project

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # setup
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    # validation
    - name: Validate Dictionaries
      run: ./gradlew validateDictionaries
    - name: Build Release APK
      run: ./gradlew assemble
