name: Build the Project

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # setup
    - name: Checkout project sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    # validate and build
    - name: Validate hELP
      run: ./gradlew convertHelp
    - name: Validate Downloads
      run: ./scripts/validate-downloads.sh app/languages/dictionaries download
    - name: Validate Dictionaries
      run: ./gradlew validateLanguages
    - name: Build Languages
      run: ./gradlew copyDefinitions convertHelp buildDictionaries
    - name: Lint
      run: ./gradlew lint # this actually runs mergeResources, so it must come after the dictionary tasks
    - name: Build all APK variants
      run: ./gradlew build
